apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    database: mydb
    user: admin
    secureJsonData:
      password: admin123
