stages:
    - test
    - build
    - deploy

before_script:
    - git submodule update --init

test:
    stage: test
    script: echo "Running tests"
        - cd skynet
        - git apply ../patches/skynet_load_excel.patch

build:
    stage: build
    script: 
        - echo "Building Server"
        - ./build.sh

deploy_staging:
    stage: deploy
    script:
        - echo "Deploy to staging server"
    environment:
        name: staging
        url: https://staging.example.com
    only:
    - master