/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pieces.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pieces.pb-c.h"
void   pieces_bool__init
                     (PiecesBool         *message)
{
  static const PiecesBool init_value = PIECES_BOOL__INIT;
  *message = init_value;
}
size_t pieces_bool__get_packed_size
                     (const PiecesBool *message)
{
  assert(message->base.descriptor == &pieces_bool__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_bool__pack
                     (const PiecesBool *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_bool__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_bool__pack_to_buffer
                     (const PiecesBool *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_bool__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesBool *
       pieces_bool__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesBool *)
     protobuf_c_message_unpack (&pieces_bool__descriptor,
                                allocator, len, data);
}
void   pieces_bool__free_unpacked
                     (PiecesBool *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_bool__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_int32__init
                     (PiecesInt32         *message)
{
  static const PiecesInt32 init_value = PIECES_INT32__INIT;
  *message = init_value;
}
size_t pieces_int32__get_packed_size
                     (const PiecesInt32 *message)
{
  assert(message->base.descriptor == &pieces_int32__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_int32__pack
                     (const PiecesInt32 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_int32__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_int32__pack_to_buffer
                     (const PiecesInt32 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_int32__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesInt32 *
       pieces_int32__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesInt32 *)
     protobuf_c_message_unpack (&pieces_int32__descriptor,
                                allocator, len, data);
}
void   pieces_int32__free_unpacked
                     (PiecesInt32 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_int32__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_int64__init
                     (PiecesInt64         *message)
{
  static const PiecesInt64 init_value = PIECES_INT64__INIT;
  *message = init_value;
}
size_t pieces_int64__get_packed_size
                     (const PiecesInt64 *message)
{
  assert(message->base.descriptor == &pieces_int64__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_int64__pack
                     (const PiecesInt64 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_int64__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_int64__pack_to_buffer
                     (const PiecesInt64 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_int64__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesInt64 *
       pieces_int64__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesInt64 *)
     protobuf_c_message_unpack (&pieces_int64__descriptor,
                                allocator, len, data);
}
void   pieces_int64__free_unpacked
                     (PiecesInt64 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_int64__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_data__init
                     (PiecesData         *message)
{
  static const PiecesData init_value = PIECES_DATA__INIT;
  *message = init_value;
}
size_t pieces_data__get_packed_size
                     (const PiecesData *message)
{
  assert(message->base.descriptor == &pieces_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_data__pack
                     (const PiecesData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_data__pack_to_buffer
                     (const PiecesData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesData *
       pieces_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesData *)
     protobuf_c_message_unpack (&pieces_data__descriptor,
                                allocator, len, data);
}
void   pieces_data__free_unpacked
                     (PiecesData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pieces_bool__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PiecesBool, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PiecesBool, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_bool__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pieces_bool__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pieces_bool__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesBool",
  "PiecesBool",
  "PiecesBool",
  "",
  sizeof(PiecesBool),
  2,
  pieces_bool__field_descriptors,
  pieces_bool__field_indices_by_name,
  1,  pieces_bool__number_ranges,
  (ProtobufCMessageInit) pieces_bool__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_int32__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PiecesInt32, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PiecesInt32, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_int32__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pieces_int32__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pieces_int32__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesInt32",
  "PiecesInt32",
  "PiecesInt32",
  "",
  sizeof(PiecesInt32),
  2,
  pieces_int32__field_descriptors,
  pieces_int32__field_indices_by_name,
  1,  pieces_int32__number_ranges,
  (ProtobufCMessageInit) pieces_int32__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_int64__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PiecesInt64, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(PiecesInt64, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_int64__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pieces_int64__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pieces_int64__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesInt64",
  "PiecesInt64",
  "PiecesInt64",
  "",
  sizeof(PiecesInt64),
  2,
  pieces_int64__field_descriptors,
  pieces_int64__field_indices_by_name,
  1,  pieces_int64__number_ranges,
  (ProtobufCMessageInit) pieces_int64__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_data__field_descriptors[3] =
{
  {
    "bool_data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PiecesData, n_bool_data),
    offsetof(PiecesData, bool_data),
    &pieces_bool__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int32_data",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PiecesData, n_int32_data),
    offsetof(PiecesData, int32_data),
    &pieces_int32__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int64_data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PiecesData, n_int64_data),
    offsetof(PiecesData, int64_data),
    &pieces_int64__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_data__field_indices_by_name[] = {
  0,   /* field[0] = bool_data */
  1,   /* field[1] = int32_data */
  2,   /* field[2] = int64_data */
};
static const ProtobufCIntRange pieces_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pieces_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pieces_data",
  "PiecesData",
  "PiecesData",
  "",
  sizeof(PiecesData),
  3,
  pieces_data__field_descriptors,
  pieces_data__field_indices_by_name,
  1,  pieces_data__number_ranges,
  (ProtobufCMessageInit) pieces_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pieces_type__enum_values_by_number[2] =
{
  { "UNKNOWN", "PIECES_TYPE__UNKNOWN", 0 },
  { "USER", "PIECES_TYPE__USER", 1 },
};
static const ProtobufCIntRange pieces_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex pieces_type__enum_values_by_name[2] =
{
  { "UNKNOWN", 0 },
  { "USER", 1 },
};
const ProtobufCEnumDescriptor pieces_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PiecesType",
  "PiecesType",
  "PiecesType",
  "",
  2,
  pieces_type__enum_values_by_number,
  2,
  pieces_type__enum_values_by_name,
  1,
  pieces_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
