/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pieces.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pieces.pb-c.h"
void   pieces_flag_data_item__init
                     (PiecesFlagDataItem         *message)
{
  static const PiecesFlagDataItem init_value = PIECES_FLAG_DATA_ITEM__INIT;
  *message = init_value;
}
size_t pieces_flag_data_item__get_packed_size
                     (const PiecesFlagDataItem *message)
{
  assert(message->base.descriptor == &pieces_flag_data_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_flag_data_item__pack
                     (const PiecesFlagDataItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_flag_data_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_flag_data_item__pack_to_buffer
                     (const PiecesFlagDataItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_flag_data_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesFlagDataItem *
       pieces_flag_data_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesFlagDataItem *)
     protobuf_c_message_unpack (&pieces_flag_data_item__descriptor,
                                allocator, len, data);
}
void   pieces_flag_data_item__free_unpacked
                     (PiecesFlagDataItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_flag_data_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_excel_data_item__init
                     (PiecesExcelDataItem         *message)
{
  static const PiecesExcelDataItem init_value = PIECES_EXCEL_DATA_ITEM__INIT;
  *message = init_value;
}
size_t pieces_excel_data_item__get_packed_size
                     (const PiecesExcelDataItem *message)
{
  assert(message->base.descriptor == &pieces_excel_data_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_excel_data_item__pack
                     (const PiecesExcelDataItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_excel_data_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_excel_data_item__pack_to_buffer
                     (const PiecesExcelDataItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_excel_data_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesExcelDataItem *
       pieces_excel_data_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesExcelDataItem *)
     protobuf_c_message_unpack (&pieces_excel_data_item__descriptor,
                                allocator, len, data);
}
void   pieces_excel_data_item__free_unpacked
                     (PiecesExcelDataItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_excel_data_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   piece_excel_data__item_entry__init
                     (PieceExcelData__ItemEntry         *message)
{
  static const PieceExcelData__ItemEntry init_value = PIECE_EXCEL_DATA__ITEM_ENTRY__INIT;
  *message = init_value;
}
void   piece_excel_data__init
                     (PieceExcelData         *message)
{
  static const PieceExcelData init_value = PIECE_EXCEL_DATA__INIT;
  *message = init_value;
}
size_t piece_excel_data__get_packed_size
                     (const PieceExcelData *message)
{
  assert(message->base.descriptor == &piece_excel_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t piece_excel_data__pack
                     (const PieceExcelData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &piece_excel_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t piece_excel_data__pack_to_buffer
                     (const PieceExcelData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &piece_excel_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PieceExcelData *
       piece_excel_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PieceExcelData *)
     protobuf_c_message_unpack (&piece_excel_data__descriptor,
                                allocator, len, data);
}
void   piece_excel_data__free_unpacked
                     (PieceExcelData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &piece_excel_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_flag_data__item_entry__init
                     (PiecesFlagData__ItemEntry         *message)
{
  static const PiecesFlagData__ItemEntry init_value = PIECES_FLAG_DATA__ITEM_ENTRY__INIT;
  *message = init_value;
}
void   pieces_flag_data__init
                     (PiecesFlagData         *message)
{
  static const PiecesFlagData init_value = PIECES_FLAG_DATA__INIT;
  *message = init_value;
}
size_t pieces_flag_data__get_packed_size
                     (const PiecesFlagData *message)
{
  assert(message->base.descriptor == &pieces_flag_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_flag_data__pack
                     (const PiecesFlagData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_flag_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_flag_data__pack_to_buffer
                     (const PiecesFlagData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_flag_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesFlagData *
       pieces_flag_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesFlagData *)
     protobuf_c_message_unpack (&pieces_flag_data__descriptor,
                                allocator, len, data);
}
void   pieces_flag_data__free_unpacked
                     (PiecesFlagData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_flag_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_link__init
                     (PiecesLink         *message)
{
  static const PiecesLink init_value = PIECES_LINK__INIT;
  *message = init_value;
}
size_t pieces_link__get_packed_size
                     (const PiecesLink *message)
{
  assert(message->base.descriptor == &pieces_link__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_link__pack
                     (const PiecesLink *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_link__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_link__pack_to_buffer
                     (const PiecesLink *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_link__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesLink *
       pieces_link__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesLink *)
     protobuf_c_message_unpack (&pieces_link__descriptor,
                                allocator, len, data);
}
void   pieces_link__free_unpacked
                     (PiecesLink *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_link__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pieces_flag_data_item__field_descriptors[2] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(PiecesFlagDataItem, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PiecesFlagDataItem, str),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_flag_data_item__field_indices_by_name[] = {
  0,   /* field[0] = number */
  1,   /* field[1] = str */
};
static const ProtobufCIntRange pieces_flag_data_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pieces_flag_data_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesFlagDataItem",
  "PiecesFlagDataItem",
  "PiecesFlagDataItem",
  "",
  sizeof(PiecesFlagDataItem),
  2,
  pieces_flag_data_item__field_descriptors,
  pieces_flag_data_item__field_indices_by_name,
  1,  pieces_flag_data_item__number_ranges,
  (ProtobufCMessageInit) pieces_flag_data_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_excel_data_item__field_descriptors[4] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(PiecesExcelDataItem, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PiecesExcelDataItem, str),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number_list",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(PiecesExcelDataItem, n_number_list),
    offsetof(PiecesExcelDataItem, number_list),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str_list",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(PiecesExcelDataItem, n_str_list),
    offsetof(PiecesExcelDataItem, str_list),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_excel_data_item__field_indices_by_name[] = {
  0,   /* field[0] = number */
  2,   /* field[2] = number_list */
  1,   /* field[1] = str */
  3,   /* field[3] = str_list */
};
static const ProtobufCIntRange pieces_excel_data_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pieces_excel_data_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesExcelDataItem",
  "PiecesExcelDataItem",
  "PiecesExcelDataItem",
  "",
  sizeof(PiecesExcelDataItem),
  4,
  pieces_excel_data_item__field_descriptors,
  pieces_excel_data_item__field_indices_by_name,
  1,  pieces_excel_data_item__number_ranges,
  (ProtobufCMessageInit) pieces_excel_data_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor piece_excel_data__item_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PieceExcelData__ItemEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PieceExcelData__ItemEntry, value),
    &pieces_excel_data_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned piece_excel_data__item_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange piece_excel_data__item_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor piece_excel_data__item_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PieceExcelData.ItemEntry",
  "ItemEntry",
  "PieceExcelData__ItemEntry",
  "",
  sizeof(PieceExcelData__ItemEntry),
  2,
  piece_excel_data__item_entry__field_descriptors,
  piece_excel_data__item_entry__field_indices_by_name,
  1,  piece_excel_data__item_entry__number_ranges,
  (ProtobufCMessageInit) piece_excel_data__item_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor piece_excel_data__field_descriptors[1] =
{
  {
    "item",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PieceExcelData, n_item),
    offsetof(PieceExcelData, item),
    &piece_excel_data__item_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned piece_excel_data__field_indices_by_name[] = {
  0,   /* field[0] = item */
};
static const ProtobufCIntRange piece_excel_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor piece_excel_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PieceExcelData",
  "PieceExcelData",
  "PieceExcelData",
  "",
  sizeof(PieceExcelData),
  1,
  piece_excel_data__field_descriptors,
  piece_excel_data__field_indices_by_name,
  1,  piece_excel_data__number_ranges,
  (ProtobufCMessageInit) piece_excel_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_flag_data__item_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PiecesFlagData__ItemEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PiecesFlagData__ItemEntry, value),
    &pieces_flag_data_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_flag_data__item_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange pieces_flag_data__item_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pieces_flag_data__item_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesFlagData.ItemEntry",
  "ItemEntry",
  "PiecesFlagData__ItemEntry",
  "",
  sizeof(PiecesFlagData__ItemEntry),
  2,
  pieces_flag_data__item_entry__field_descriptors,
  pieces_flag_data__item_entry__field_indices_by_name,
  1,  pieces_flag_data__item_entry__number_ranges,
  (ProtobufCMessageInit) pieces_flag_data__item_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_flag_data__field_descriptors[1] =
{
  {
    "item",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PiecesFlagData, n_item),
    offsetof(PiecesFlagData, item),
    &pieces_flag_data__item_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_flag_data__field_indices_by_name[] = {
  0,   /* field[0] = item */
};
static const ProtobufCIntRange pieces_flag_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pieces_flag_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesFlagData",
  "PiecesFlagData",
  "PiecesFlagData",
  "",
  sizeof(PiecesFlagData),
  1,
  pieces_flag_data__field_descriptors,
  pieces_flag_data__field_indices_by_name,
  1,  pieces_flag_data__number_ranges,
  (ProtobufCMessageInit) pieces_flag_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_link__field_descriptors[3] =
{
  {
    "data_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PiecesLink, data_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PiecesLink, next),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PiecesLink, n_data),
    offsetof(PiecesLink, data),
    &pieces_flag_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_link__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = data_type */
  1,   /* field[1] = next */
};
static const ProtobufCIntRange pieces_link__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pieces_link__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesLink",
  "PiecesLink",
  "PiecesLink",
  "",
  sizeof(PiecesLink),
  3,
  pieces_link__field_descriptors,
  pieces_link__field_indices_by_name,
  1,  pieces_link__number_ranges,
  (ProtobufCMessageInit) pieces_link__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pieces_type__enum_values_by_number[2] =
{
  { "UNKNOWN", "PIECES_TYPE__UNKNOWN", 0 },
  { "USER", "PIECES_TYPE__USER", 1 },
};
static const ProtobufCIntRange pieces_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex pieces_type__enum_values_by_name[2] =
{
  { "UNKNOWN", 0 },
  { "USER", 1 },
};
const ProtobufCEnumDescriptor pieces_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PiecesType",
  "PiecesType",
  "PiecesType",
  "",
  2,
  pieces_type__enum_values_by_number,
  2,
  pieces_type__enum_values_by_name,
  1,
  pieces_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
