/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pieces.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pieces.pb-c.h"
void   pieces_int32__init
                     (PiecesInt32         *message)
{
  static const PiecesInt32 init_value = PIECES_INT32__INIT;
  *message = init_value;
}
size_t pieces_int32__get_packed_size
                     (const PiecesInt32 *message)
{
  assert(message->base.descriptor == &pieces_int32__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_int32__pack
                     (const PiecesInt32 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_int32__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_int32__pack_to_buffer
                     (const PiecesInt32 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_int32__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesInt32 *
       pieces_int32__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesInt32 *)
     protobuf_c_message_unpack (&pieces_int32__descriptor,
                                allocator, len, data);
}
void   pieces_int32__free_unpacked
                     (PiecesInt32 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_int32__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_int64__init
                     (PiecesInt64         *message)
{
  static const PiecesInt64 init_value = PIECES_INT64__INIT;
  *message = init_value;
}
size_t pieces_int64__get_packed_size
                     (const PiecesInt64 *message)
{
  assert(message->base.descriptor == &pieces_int64__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_int64__pack
                     (const PiecesInt64 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_int64__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_int64__pack_to_buffer
                     (const PiecesInt64 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_int64__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesInt64 *
       pieces_int64__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesInt64 *)
     protobuf_c_message_unpack (&pieces_int64__descriptor,
                                allocator, len, data);
}
void   pieces_int64__free_unpacked
                     (PiecesInt64 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_int64__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_string__init
                     (PiecesString         *message)
{
  static const PiecesString init_value = PIECES_STRING__INIT;
  *message = init_value;
}
size_t pieces_string__get_packed_size
                     (const PiecesString *message)
{
  assert(message->base.descriptor == &pieces_string__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_string__pack
                     (const PiecesString *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_string__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_string__pack_to_buffer
                     (const PiecesString *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_string__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesString *
       pieces_string__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesString *)
     protobuf_c_message_unpack (&pieces_string__descriptor,
                                allocator, len, data);
}
void   pieces_string__free_unpacked
                     (PiecesString *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_string__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_excel_data_item__init
                     (PiecesExcelDataItem         *message)
{
  static const PiecesExcelDataItem init_value = PIECES_EXCEL_DATA_ITEM__INIT;
  *message = init_value;
}
size_t pieces_excel_data_item__get_packed_size
                     (const PiecesExcelDataItem *message)
{
  assert(message->base.descriptor == &pieces_excel_data_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_excel_data_item__pack
                     (const PiecesExcelDataItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_excel_data_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_excel_data_item__pack_to_buffer
                     (const PiecesExcelDataItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_excel_data_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesExcelDataItem *
       pieces_excel_data_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesExcelDataItem *)
     protobuf_c_message_unpack (&pieces_excel_data_item__descriptor,
                                allocator, len, data);
}
void   pieces_excel_data_item__free_unpacked
                     (PiecesExcelDataItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_excel_data_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   piece_excel_data__init
                     (PieceExcelData         *message)
{
  static const PieceExcelData init_value = PIECE_EXCEL_DATA__INIT;
  *message = init_value;
}
size_t piece_excel_data__get_packed_size
                     (const PieceExcelData *message)
{
  assert(message->base.descriptor == &piece_excel_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t piece_excel_data__pack
                     (const PieceExcelData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &piece_excel_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t piece_excel_data__pack_to_buffer
                     (const PieceExcelData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &piece_excel_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PieceExcelData *
       piece_excel_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PieceExcelData *)
     protobuf_c_message_unpack (&piece_excel_data__descriptor,
                                allocator, len, data);
}
void   piece_excel_data__free_unpacked
                     (PieceExcelData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &piece_excel_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_flag_data__init
                     (PiecesFlagData         *message)
{
  static const PiecesFlagData init_value = PIECES_FLAG_DATA__INIT;
  *message = init_value;
}
size_t pieces_flag_data__get_packed_size
                     (const PiecesFlagData *message)
{
  assert(message->base.descriptor == &pieces_flag_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_flag_data__pack
                     (const PiecesFlagData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_flag_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_flag_data__pack_to_buffer
                     (const PiecesFlagData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_flag_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesFlagData *
       pieces_flag_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesFlagData *)
     protobuf_c_message_unpack (&pieces_flag_data__descriptor,
                                allocator, len, data);
}
void   pieces_flag_data__free_unpacked
                     (PiecesFlagData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_flag_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pieces_link__init
                     (PiecesLink         *message)
{
  static const PiecesLink init_value = PIECES_LINK__INIT;
  *message = init_value;
}
size_t pieces_link__get_packed_size
                     (const PiecesLink *message)
{
  assert(message->base.descriptor == &pieces_link__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pieces_link__pack
                     (const PiecesLink *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pieces_link__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pieces_link__pack_to_buffer
                     (const PiecesLink *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pieces_link__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PiecesLink *
       pieces_link__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PiecesLink *)
     protobuf_c_message_unpack (&pieces_link__descriptor,
                                allocator, len, data);
}
void   pieces_link__free_unpacked
                     (PiecesLink *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pieces_link__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pieces_int32__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PiecesInt32, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PiecesInt32, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_int32__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pieces_int32__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pieces_int32__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesInt32",
  "PiecesInt32",
  "PiecesInt32",
  "",
  sizeof(PiecesInt32),
  2,
  pieces_int32__field_descriptors,
  pieces_int32__field_indices_by_name,
  1,  pieces_int32__number_ranges,
  (ProtobufCMessageInit) pieces_int32__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_int64__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PiecesInt64, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(PiecesInt64, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_int64__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pieces_int64__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pieces_int64__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesInt64",
  "PiecesInt64",
  "PiecesInt64",
  "",
  sizeof(PiecesInt64),
  2,
  pieces_int64__field_descriptors,
  pieces_int64__field_indices_by_name,
  1,  pieces_int64__number_ranges,
  (ProtobufCMessageInit) pieces_int64__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_string__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PiecesString, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PiecesString, data),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_string__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pieces_string__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pieces_string__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesString",
  "PiecesString",
  "PiecesString",
  "",
  sizeof(PiecesString),
  2,
  pieces_string__field_descriptors,
  pieces_string__field_indices_by_name,
  1,  pieces_string__number_ranges,
  (ProtobufCMessageInit) pieces_string__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_excel_data_item__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PiecesExcelDataItem, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(PiecesExcelDataItem, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PiecesExcelDataItem, str),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number_list",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(PiecesExcelDataItem, n_number_list),
    offsetof(PiecesExcelDataItem, number_list),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str_list",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(PiecesExcelDataItem, n_str_list),
    offsetof(PiecesExcelDataItem, str_list),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_excel_data_item__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = number */
  3,   /* field[3] = number_list */
  2,   /* field[2] = str */
  4,   /* field[4] = str_list */
};
static const ProtobufCIntRange pieces_excel_data_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor pieces_excel_data_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesExcelDataItem",
  "PiecesExcelDataItem",
  "PiecesExcelDataItem",
  "",
  sizeof(PiecesExcelDataItem),
  5,
  pieces_excel_data_item__field_descriptors,
  pieces_excel_data_item__field_indices_by_name,
  1,  pieces_excel_data_item__number_ranges,
  (ProtobufCMessageInit) pieces_excel_data_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor piece_excel_data__field_descriptors[1] =
{
  {
    "item",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PieceExcelData, n_item),
    offsetof(PieceExcelData, item),
    &pieces_excel_data_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned piece_excel_data__field_indices_by_name[] = {
  0,   /* field[0] = item */
};
static const ProtobufCIntRange piece_excel_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor piece_excel_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PieceExcelData",
  "PieceExcelData",
  "PieceExcelData",
  "",
  sizeof(PieceExcelData),
  1,
  piece_excel_data__field_descriptors,
  piece_excel_data__field_indices_by_name,
  1,  piece_excel_data__number_ranges,
  (ProtobufCMessageInit) piece_excel_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_flag_data__field_descriptors[3] =
{
  {
    "int32_data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PiecesFlagData, n_int32_data),
    offsetof(PiecesFlagData, int32_data),
    &pieces_int32__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int64_data",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PiecesFlagData, n_int64_data),
    offsetof(PiecesFlagData, int64_data),
    &pieces_int64__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PiecesFlagData, n_string_data),
    offsetof(PiecesFlagData, string_data),
    &pieces_string__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_flag_data__field_indices_by_name[] = {
  0,   /* field[0] = int32_data */
  1,   /* field[1] = int64_data */
  2,   /* field[2] = string_data */
};
static const ProtobufCIntRange pieces_flag_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pieces_flag_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesFlagData",
  "PiecesFlagData",
  "PiecesFlagData",
  "",
  sizeof(PiecesFlagData),
  3,
  pieces_flag_data__field_descriptors,
  pieces_flag_data__field_indices_by_name,
  1,  pieces_flag_data__number_ranges,
  (ProtobufCMessageInit) pieces_flag_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pieces_link__field_descriptors[3] =
{
  {
    "data_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PiecesLink, data_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PiecesLink, next),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PiecesLink, n_data),
    offsetof(PiecesLink, data),
    &pieces_flag_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pieces_link__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = data_type */
  1,   /* field[1] = next */
};
static const ProtobufCIntRange pieces_link__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pieces_link__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PiecesLink",
  "PiecesLink",
  "PiecesLink",
  "",
  sizeof(PiecesLink),
  3,
  pieces_link__field_descriptors,
  pieces_link__field_indices_by_name,
  1,  pieces_link__number_ranges,
  (ProtobufCMessageInit) pieces_link__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pieces_type__enum_values_by_number[2] =
{
  { "UNKNOWN", "PIECES_TYPE__UNKNOWN", 0 },
  { "USER", "PIECES_TYPE__USER", 1 },
};
static const ProtobufCIntRange pieces_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex pieces_type__enum_values_by_name[2] =
{
  { "UNKNOWN", 0 },
  { "USER", 1 },
};
const ProtobufCEnumDescriptor pieces_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PiecesType",
  "PiecesType",
  "PiecesType",
  "",
  2,
  pieces_type__enum_values_by_number,
  2,
  pieces_type__enum_values_by_name,
  1,
  pieces_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
